# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Microsoft Partner Network (ashworth)(f0f6b991-5cad-414a-9783-ddb36a291045)'
    subscriptionId: 'f0f6b991-5cad-414a-9783-ddb36a291045'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-sfc-azureenv'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'azenv/azuredeploy.json'
    overrideParameters: '-projectName sfc-azureenv -linkedtemplateuri https://github.com/heuristik1/sfc'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'